# Change these first
owner: vurilo # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Web app
    url: $URL_SITE
  - name: Image Service
    url: $URL_IMAGE_SERVICE
  - name: Rest API
    url: $URL_REST_API

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.vurilo.com
  # baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Vurilo Status
  introTitle: "Status all parts of **Vurilo** platform"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: Vurilo
      href: https://vurilo.com
  metaTags:
    - name: descrition
      content: Welcome to Vurilo&#39;s home for real-time and historical data on system performance.
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
assignees:
  - sursaone
i18n:
  footer: &#169 vurilo.com
  
